# Generated by Django 4.2.29 on 2026-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url_external',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
